wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1649145603
    t:
      1:
      - 1
      4: 3.8.13
      5: 0.12.11
      8:
      - 3
      - 5
